# Generated by Django 5.1 on 2025-01-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='books/default_cover.png', upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
